#!/bin/bash

git rm tomee/modules/ROOT/pages/articles.adoc
git rm tomee/modules/ROOT/pages/azure.adoc
git rm tomee/modules/ROOT/pages/commercial-support.adoc
git rm tomee/modules/ROOT/pages/comparison.adoc
git rm tomee/modules/ROOT/pages/concepts.adoc
git rm tomee/modules/ROOT/pages/contribute.adoc
git rm tomee/modules/ROOT/pages/dev/april2008.adoc
git rm tomee/modules/ROOT/pages/dev/april2009.adoc
git rm tomee/modules/ROOT/pages/dev/arquillian-test-porting-initiative.adoc
git rm tomee/modules/ROOT/pages/dev/asf.adoc
git rm tomee/modules/ROOT/pages/dev/august2007.adoc
git rm tomee/modules/ROOT/pages/dev/building-from-source.adoc
git rm tomee/modules/ROOT/pages/dev/cdi-tck-webappsdeployer.adoc
git rm tomee/modules/ROOT/pages/dev/configuration-and-assembly.adoc
git rm tomee/modules/ROOT/pages/dev/contribution-tips.adoc
git rm tomee/modules/ROOT/pages/dev/creating-itests.adoc
git rm tomee/modules/ROOT/pages/dev/design.adoc
git rm tomee/modules/ROOT/pages/dev/design-application-server.adoc
git rm tomee/modules/ROOT/pages/dev/design-application-serverlinks.adoc
git rm tomee/modules/ROOT/pages/dev/design-assembler.adoc
git rm tomee/modules/ROOT/pages/dev/design-bmp-entitybean-container.adoc
git rm tomee/modules/ROOT/pages/dev/design-classic-assembler.adoc
git rm tomee/modules/ROOT/pages/dev/design-cmp-entitybean-container.adoc
git rm tomee/modules/ROOT/pages/dev/design-configuration-factory.adoc
git rm tomee/modules/ROOT/pages/dev/design-container.adoc
git rm tomee/modules/ROOT/pages/dev/design-local-server.adoc
git rm tomee/modules/ROOT/pages/dev/design-local-serverlinks.adoc
git rm tomee/modules/ROOT/pages/dev/design-nova-configuration-factory.adoc
git rm tomee/modules/ROOT/pages/dev/design-passivation-strategy.adoc
git rm tomee/modules/ROOT/pages/dev/design-random-access-file-passivater.adoc
git rm tomee/modules/ROOT/pages/dev/design-remote-server.adoc
git rm tomee/modules/ROOT/pages/dev/design-remote-serverlinks.adoc
git rm tomee/modules/ROOT/pages/dev/design-resource-manager.adoc
git rm tomee/modules/ROOT/pages/dev/design-security-service.adoc
git rm tomee/modules/ROOT/pages/dev/design-simple-passivater.adoc
git rm tomee/modules/ROOT/pages/dev/design-stateful-sessionbean-container.adoc
git rm tomee/modules/ROOT/pages/dev/design-stateless-sessionbean-container.adoc
git rm tomee/modules/ROOT/pages/dev/design-transaction-service.adoc
git rm tomee/modules/ROOT/pages/dev/git.adoc
git rm tomee/modules/ROOT/pages/dev/itests-overview.adoc
git rm tomee/modules/ROOT/pages/dev/january2008.adoc
git rm tomee/modules/ROOT/pages/dev/january2010.adoc
git rm tomee/modules/ROOT/pages/dev/july2007.adoc
git rm tomee/modules/ROOT/pages/dev/july2008.adoc
git rm tomee/modules/ROOT/pages/dev/july2009.adoc
git rm tomee/modules/ROOT/pages/dev/july2010.adoc
git rm tomee/modules/ROOT/pages/dev/june2007.adoc
git rm tomee/modules/ROOT/pages/dev/logging.adoc
git rm tomee/modules/ROOT/pages/dev/mastering-the-command-line.adoc
git rm tomee/modules/ROOT/pages/dev/october2007.adoc
git rm tomee/modules/ROOT/pages/dev/october2008.adoc
git rm tomee/modules/ROOT/pages/dev/october2009.adoc
git rm tomee/modules/ROOT/pages/dev/openejb-release-process.adoc
git rm tomee/modules/ROOT/pages/dev/proxies.adoc
git rm tomee/modules/ROOT/pages/dev/release-tomee.adoc
git rm tomee/modules/ROOT/pages/dev/roadmap.adoc
git rm tomee/modules/ROOT/pages/dev/rsync.adoc
git rm tomee/modules/ROOT/pages/dev/rules-of-thumb.adoc
git rm tomee/modules/ROOT/pages/dev/source-code.adoc
git rm tomee/modules/ROOT/pages/dev/take-my-code.adoc
git rm tomee/modules/ROOT/pages/dev/thread-dumps.adoc
git rm tomee/modules/ROOT/pages/dev/validation-keys-audit-report.adoc
git rm tomee/modules/ROOT/pages/dev/website-dev.adoc
git rm tomee/modules/ROOT/pages/dev/writing-examples.adoc
git rm tomee/modules/ROOT/pages/dev/writing-validation-tests.adoc
git rm tomee/modules/ROOT/pages/dev/xbean-finder.adoc
git rm tomee/modules/ROOT/pages/dev/xbean-usage-in-openejb.adoc
git rm tomee/modules/ROOT/pages/enterprise-tomcat.adoc
git rm tomee/modules/ROOT/pages/evolution-of-ejb.adoc
git rm tomee/modules/ROOT/pages/examples/buildbot.adoc
git rm tomee/modules/ROOT/pages/faq.adoc
git rm tomee/modules/ROOT/pages/features.adoc
git rm tomee/modules/ROOT/pages/geronimo.adoc
git rm tomee/modules/ROOT/pages/getting-started-with-eclipse-and-webby.adoc
git rm tomee/modules/ROOT/pages/lightening-demos.adoc
git rm tomee/modules/ROOT/pages/mailing-lists.adoc
git rm tomee/modules/ROOT/pages/management-and-voting.adoc
git rm tomee/modules/ROOT/pages/powered-by.adoc
git rm tomee/modules/ROOT/pages/privacy-policy.adoc
git rm tomee/modules/ROOT/pages/security/tomee.adoc
git rm tomee/modules/ROOT/pages/support.adoc
git rm tomee/modules/ROOT/pages/team.adoc
git rm tomee/modules/ROOT/pages/testcase-with-testbean-inner-class.adoc
git rm tomee/modules/ROOT/pages/tomcat.adoc
git rm tomee/modules/ROOT/pages/tomcat-activemq.adoc
git rm tomee/modules/ROOT/pages/tomcat-cdi.adoc
git rm tomee/modules/ROOT/pages/tomcat-detailed-instructions.adoc
git rm tomee/modules/ROOT/pages/tomcat-ejb.adoc
git rm tomee/modules/ROOT/pages/tomcat-ejb-refs.adoc
git rm tomee/modules/ROOT/pages/tomcat-installation.adoc
git rm tomee/modules/ROOT/pages/tomcat-java-ee.adoc
git rm tomee/modules/ROOT/pages/tomcat-javaee.adoc
git rm tomee/modules/ROOT/pages/tomcat-jaxrs.adoc
git rm tomee/modules/ROOT/pages/tomcat-jaxws.adoc
git rm tomee/modules/ROOT/pages/tomcat-jms.adoc
git rm tomee/modules/ROOT/pages/tomcat-jpa.adoc
git rm tomee/modules/ROOT/pages/tomcat-jsf.adoc
git rm tomee/modules/ROOT/pages/tomcat-object-factory.adoc
git rm tomee/modules/ROOT/pages/tomee-1.0.0-beta-1.adoc
git rm tomee/modules/ROOT/pages/tomee-1.5.0.adoc
git rm tomee/modules/ROOT/pages/tomee-1.5.0-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.5.1.adoc
git rm tomee/modules/ROOT/pages/tomee-1.5.1-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.6.0.1.adoc
git rm tomee/modules/ROOT/pages/tomee-1.6.0.1-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.6.0.2.adoc
git rm tomee/modules/ROOT/pages/tomee-1.6.0.2-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.0.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.0-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.1.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.1-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.2.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.2-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.3.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.3-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-1.7.4.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M1.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M1-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M2.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M2-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M3.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-M3-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.0-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.1.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.1-release-notes.adoc
git rm tomee/modules/ROOT/pages/tomee-7.0.2-release-notes.adoc
git rm tomee/modules/ROOT/pages/unit-testing-transactions.adoc
git rm tomee/modules/ROOT/pages/webadmin.adoc
git rm tomee/modules/ROOT/pages/webobjects.adoc
