= TomEE Maven Plugin
:index-group: Unrevised
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published

Inspired by the Jetty Maven Plugin, the TomEE Maven Plugin is a feature-rich plugin that allows for:

* Easy provisioning of a TomEE server
* Server start and stop
* Application deployment and undeployment

Simply add the following to the +++<plugins>+++, and optionally the +++<pluginManagement>+++), section of your `pom.xml`+++</pluginManagement>++++++</plugins>+++

 <plugins>
     <plugin>
       <groupId>org.apache.openejb.maven</groupId>
       <artifactId>tomee-maven-plugin</artifactId>
       <version>1.7.1</version>
       <configuration>
         <tomeeVersion>1.7.1</tomeeVersion>
         <tomeeClassifier>plus</tomeeClassifier>
       </configuration>
     </plugin>
 </plugins>

###Plugin Goals+++<table border="0" class="bodyTable">++++++<tr class="a">+++
|Goal

|Description
+++<tr class="b">+++
|+++<a href="build-mojo.html">+++tomee:build+++</a>+++

|Create TomEE, but do not run it.
+++<tr class="a">+++
|+++<a href="configtest-mojo.html">+++tomee:configtest+++</a>+++

|Run the Apache Tomcat `configtest` command.
+++<tr class="b">+++
|+++<a href="debug-mojo.html">+++tomee:debug+++</a>+++

|Same as `run` but with debug activated on the default or specified port.
+++<tr class="a">+++
|+++<a href="deploy-mojo.html">+++tomee:deploy+++</a>+++

|Deploy an application in a running TomEE.
+++<tr class="b">+++
|+++<a href="exec-mojo.html">+++tomee:exec+++</a>+++

|Undocumented.
+++<tr class="a">+++
|+++<a href="help-mojo.html">+++tomee:help+++</a>+++

|Display help information on the tomee-maven-plugin.+++<br>++++++</br>+++
Call +++<code>+++mvn tomee:help -Ddetail=true
-Dgoal=<goal-name>+++</code>+++ to display parameter details.
+++<tr class="b">+++
|+++<a href="list-mojo.html">+++tomee:list+++</a>+++

|Largely inspired by the OpenEJB command helper, but with some differences. List deployed EJB's in a running TomEE.
+++<tr class="a">+++
|+++<a href="run-mojo.html">+++tomee:run+++</a>+++

|Start and wait for TomEE.
+++<tr class="b">+++
|+++<a href="start-mojo.html">+++tomee:start+++</a>+++

|Start TomEE and continue.
+++<tr class="a">+++
|+++<a href="stop-mojo.html">+++tomee:stop+++</a>+++

|Stop a TomEE started with start command.
+++<tr class="b">+++
|+++<a href="undeploy-mojo.html">+++tomee:undeploy+++</a>+++

|Undeploy an application in a running TomEE
|===


Note that for the tomee:deploy and tomee:undeploy goals, the path can either be specified within the +++<configuration>++++++</configuration>+++ section of the `pom.xml` using the +++<path>+++parameter, or it can be passed via the user property tomee-plugin.archive.
If a relative path is passed for the deploy path archive, this must be relative to the TomEE server.+++</path>+++

Note 2: running tomee maven plugin you can type 'quit' directly in the console to shutdown correctly the server.
'reload' is also available when internal openejb application is deployed.

###More Tweaks

The lib tag allows to enrich the container with some additional libraries.

Some interesting patterns in addition to the default maven formats are supported.

* remove:<some prefix of jar in lib folder>: remove all jar starting with the specified prefix
* unzip:<some maven zip>: extract the zip in lib folder
* ?name=<new-name>: rename the libary once copied in lib folder

NOTE: the name tweak can be used to rename applications too

###Provisioning Example

This plugin is also usable in projects which are not war.
For instance you can use it in a pom project to setup a TomEE install, add libraries, deploy apps then run the server.

   <plugin>
     <groupId>org.apache.openejb.maven</groupId>
     <artifactId>tomee-maven-plugin</artifactId>
     <version>1.7.1</version>
     <configuration>
       <tomeeVersion>1.7.1</tomeeVersion>
       <tomeeClassifier>plus</tomeeClassifier>
       <debug>false</debug>
       <debugPort>5005</debugPort>
       <args>-Dfoo=bar</args>
       <config>${project.basedir}/src/test/tomee/conf</config>
       <libs>
         <lib>mysql:mysql-connector-java:5.1.20</lib>
       </libs>
       <webapps>
          <webapp>org.superbiz:myapp:4.3?name=ROOT</webapp>
          <webapp>org.superbiz:api:1.1</webapp>
       </webapps>
       <apps>
           <app>org.superbiz:mybugapp:3.2:ear</app>
       </apps>
       <libs>
           <lib>mysql:mysql-connector-java:5.1.21</lib>
           <lib>unzip:org.superbiz:hibernate-bundle:4.1.0.Final:zip</lib>
           <lib>remove:openjpa-</lib>
       </libs>
     </configuration>
   </plugin>

###Auto Reloading Example

 <plugin>
   <groupId>org.apache.openejb.maven</groupId>
   <artifactId>tomee-maven-plugin</artifactId>
   <version>1.7.1</version>
   <configuration>
     <synchronization>
       <extensions>
         <extension>.class</extension> <!-- if you want to update each time you build with mvn compile -->
       </extensions>
     </synchronization>
     <reloadOnUpdate>true</reloadOnUpdate>
   </configuration>
 </plugin>

The Synchronization block supports the following configuration options:

* resourcesDir (default src/main/webapp)
* binariesDir (default target/classes)
* targetBinariesDir (default tomee/webapps/finalName/WEB-INF/classes)
* targetResourcesDir (default tomee/webapps/finalName)
* updateInterval (default 5 - in second)
* extensions (default html, xhtml, js and css)
* regex: a regex should match files to take into account when updating

reloadOnUpdate means to reload the entire context (webapp).
This means undeploying/redeploying the application.
