Title: JavaEE Examples Notice:    Licensed to the Apache Software Foundation (ASF) under one            or more contributor license agreements.
See the NOTICE file            distributed with this work for additional information            regarding copyright ownership.
The ASF licenses this file            to you under the Apache License, Version 2.0 (the            "License");
you may not use this file except in compliance            with the License.
You may obtain a copy of the License at            .              http://www.apache.org/licenses/LICENSE-2.0            .            Unless required by applicable law or agreed to in writing,            software distributed under the License is distributed on an            "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY            KIND, either express or implied.
See the License for the            specific language governing permissions and limitations            under the License.

If there is a particular example that you do not see here please feel free to link:mailto:dev@openejb.apache.org?subject=Example+request[ask], the odds are good that someone will create it for you.
+ All the examples show source code, but some are better documented than others.
If you need a little more help understanding an example then please drop us a link:mailto:dev@openejb.apache.org?subject=Example+request[line] or visit us on IRC freenode.net #openejb

{row {span-one-third ###Session Beans link:simple-singleton/README.html[simple-singleton] + link:simple-stateful/README.html[simple-stateful] + link:simple-stateless/README.html[simple-stateless] + link:simple-stateless-with-descriptor/README.html[simple-stateless-with-descriptor] + } {span-one-third ###EntityManagers link:injection-of-entitymanager/README.html[injection-of-entitymanager] + link:jpa-eclipselink/README.html[jpa-eclipselink] + link:jpa-hibernate/README.html[jpa-hibernate] + link:jpa-enumerated/README.html[jpa-enumerated] + } {span-one-third ###CDI link:cdi-basic/README.html[cdi-basic] + link:cdi-request-scope/README.html[cdi-request-scope] + link:cdi-application-scope/README.html[cdi-application-scope] + link:simple-cdi-interceptor/README.html[simple-cdi-interceptor] + link:cdi-produces-disposes/README.html[cdi-produces-disposes] + link:decorators/README.html[decorators] + link:cdi-alternative-and-stereotypes/README.html[cdi-alternative-and-stereotypes] + } } {row {span-one-third ###EJB link:access-timeout/README.html[access-timeout] + link:async-methods/README.html[async-methods] + link:schedule-expression/README.html[schedule-expression] + link:schedule-methods/README.html[schedule-methods] + link:interceptors/README.html[interceptors] + link:async-postconstruct/README.html[async-postconstruct] + } {span-one-third ###REST link:simple-rest/README.html[simple-rest] + link:rest-example/README.html[rest-example] + link:rest-example-with-application/README.html[rest-example-with-application] + link:rest-on-ejb/README.html[rest-on-ejb] + link:rest-example/README.html[rest-xml-json] + } {span-one-third ###Web Services link:simple-webservice/README.html[simple-webservice] + link:webservice-handlerchain/README.html[webservice-handlerchain] + link:webservice-holder/README.html[webservice-holder] + link:webservice-attachments/README.html[webservice-attachments] + link:webservice-inheritance/README.html[webservice-inheritance] + link:webservice-security/README.html[webservice-security] + link:webservice-ws-security/README.html[webservice-ws-security] + } } {row {span-one-third ###JMS and MDBs link:injection-of-connectionfactory/README.html[injection-of-connectionfactory] + link:simple-mdb-with-descriptor/README.html[simple-mdb-with-descriptor] + link:simple-mdb/README.html[simple-mdb] + } {span-one-third

=== Transactions

link:testing-transactions/README.html[testing-transactions] + link:transaction-rollback/README.html[transaction-rollback] + link:applicationexception/README.html[applicationexception] + } {span-one-third

=== Security

link:testing-security-3/README.html[testing-security-3] + link:testing-security-2/README.html[testing-security-2] + link:testing-security/README.html[testing-security] + } } {row {span-one-third ###DataSources link:injection-of-datasource/README.html[injection-of-datasource] + link:datasource-ciphered-password/README.html[datasource-ciphered-password] + link:dynamic-datasource-routing/README.html[dynamic-datasource-routing] + link:resources-declared-in-webapp/README.html[resources-declared-in-webapp] + } {span-one-third ###Referencing EJBs link:injection-of-ejbs/README.html[injection-of-ejbs] + link:lookup-of-ejbs-with-descriptor/README.html[lookup-of-ejbs-with-descriptor] + link:lookup-of-ejbs/README.html[lookup-of-ejbs] + } {span-one-third ###Environment Entries link:injection-of-env-entry/README.html[injection-of-env-entry] + link:custom-injection/README.html[custom-injection] + } } {row {span-one-third ###Java EE Connectors link:quartz-app/README.html[quartz-app] + } {span-one-third ###Testing Techniques link:alternate-descriptors/README.html[alternate-descriptors] + link:application-composer/README.html[application-composer] + link:testcase-injection/README.html[testcase-injection] + link:ear-testing/README.html[ear-testing] + } {span-one-third

=== Frameworks

link:spring-data-proxy-meta/README.html[spring-data-proxy-meta] + link:spring-data-proxy/README.html[spring-data-proxy] + link:struts/README.html[struts] + } } {row {span-one-third ###Meta-Annotations link:access-timeout-meta/README.html[access-timeout-meta] + link:schedule-methods-meta/README.html[schedule-methods-meta] + link:testing-security-meta/README.html[testing-security-meta] + link:movies-complete-meta/README.html[movies-complete-meta] + link:movies-complete/README.html[movies-complete] + } {span-one-third

=== Proxy Beans

link:dynamic-dao-implementation/README.html[dynamic-dao-implementation] + link:dynamic-implementation/README.html[dynamic-implementation] + link:dynamic-proxy-to-access-mbean/README.html[dynamic-proxy-to-access-mbean] + link:spring-data-proxy/README.html[spring-data-proxy] + } {span-one-third ###EJB Legacy link:simple-cmp2/README.html[cmp2-entitybeans] + link:component-interfaces/README.html[component-interfaces] + } } {row {span-one-third

=== Other Features

link:mbean-auto-registration/README.html[mbean-auto-registration] + link:bean-validation-design-by-contract/README.html[bean-validation-design-by-contract] + link:telephone-stateful/README.html[telephone-stateful] + link:troubleshooting/README.html[troubleshooting] + } {span-two-thirds ###Misc link:applet/README.html[applet] + link:ejb-examples/README.html[ejb-examples] + link:ejb-webservice/README.html[ejb-webservice] + link:jsf-cdi-and-ejb/README.html[jsf-cdi-and-ejb] + link:jsf-managedBean-and-ejb/README.html[jsf-managedBean-and-ejb] + link:moviefun/README.html[moviefun] + link:helloworld-weblogic/README.html[helloworld-weblogic] + link:polling-parent/README.html[polling-parent] + } }
