:doctype: book

Title: EJB 3 RoadMap \{swizzlejira}

. set( $jira = $rss.fetch("http://issues.apache.org/jira/sr/jira.issueviews:searchrequest-xml/temp/SearchRequest.xml?&pid=12310530&component=12311366") )
. set( $axis = $rss.fetch("http://issues.apache.org/jira/si/jira.issueviews:issue-xml/OPENEJB-114/OPENEJB-114.xml") )
. set( $corba = $rss.fetch("http://issues.apache.org/jira/si/jira.issueviews:issue-xml/OPENEJB-113/OPENEJB-113.xml") )
. set( $geronimo = $rss.fetch("http://issues.apache.org/jira/si/jira.issueviews:issue-xml/OPENEJB-524/OPENEJB-524.xml") )
. set( $issues = $jira.fillSubTasks() )

+++<a name="EJB3RoadMap-EJB3.0RoadMap">++++++</a>+++

= EJB 3.0 Road Map

+++<a name="EJB3RoadMap-SimplifiedLifecycle">++++++</a>+++

== Simplified Lifecycle

. set( $lifecycle = $jira.getIssue("OPENEJB-76").subTasks)
. set( $lifecycle = $lifecycle.union($jira.getIssue("OPENEJB-77").subTasks) ) {swizzlejiraissues:issues=$as.param($lifecycle)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-DependencyInjection">++++++</a>+++

== Dependency Injection

. set( $dependencyInjection = $jira.getIssue("OPENEJB-98").subTasks)  {swizzlejiraissues:issues=$as.param($dependencyInjection)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-BusinessInterfaces">++++++</a>+++

== Business Interfaces

. set( $businessInterfaces = $jira.getIssue("OPENEJB-90").subTasks)
. set( $businessInterfaces = $businessInterfaces.union($jira.getIssue("OPENEJB-406")) ) {swizzlejiraissues:issues=$as.param($businessInterfaces)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-EJB3.0<->EJB2.1Compatability">++++++</a>+++

== EJB 3.0 \<-> EJB 2.1 Compatability

. set( $ejb2compat = $jira.getIssue("OPENEJB-89").subTasks)  {swizzlejiraissues:issues=$as.param($ejb2compat)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-Annotations">++++++</a>+++

== Annotations

. set( $annotations = $jira.getIssue("OPENEJB-216").subTasks) {swizzlejiraissues:issues=$as.param($annotations)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-JNDIENC">++++++</a>+++

== JNDI ENC

. set( $jndi = $jira.getIssue("OPENEJB-370").subTasks) {swizzlejiraissues:issues=$as.param($jndi)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-Interceptors">++++++</a>+++

== Interceptors

. set( $interceptors = $jira.getIssue("OPENEJB-79").subTasks)
. set( $interceptors = $interceptors.union($jira.getIssue("OPENEJB-78")) )
. set( $interceptors = $interceptors.union($jira.getIssue("OPENEJB-80")) ) {swizzlejiraissues:issues=$as.param($interceptors)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-Integration">++++++</a>+++

== Integration

. set( $integration = $axis.issues )
. set( $integration = $integration.union($corba.issues) )
. set( $integration = $integration.union($geronimo.issues) ) {swizzlejiraissues:issues=$as.param($integration)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-CMP2.xviaJPA">++++++</a>+++

== CMP 2.x via JPA

. set( $cmp = $rss.fetch("http://issues.apache.org/jira/si/jira.issueviews:issue-xml/OPENEJB-123/OPENEJB-123.xml") )
. set( $void = $cmp.fillSubTasks() )
. set( $cmp = $cmp.getIssue("OPENEJB-123") ) {swizzlejiraissues:issues=$as.param($cmp.subTasks)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-Validation">++++++</a>+++

== Validation

. set( $validation = $jira.getIssue("OPENEJB-453").subTasks) {swizzlejiraissues:issues=$as.param($validation)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-ComplianceTests">++++++</a>+++

== Compliance Tests

. set( $itests = $jira.getIssue("OPENEJB-142").subTasks) {swizzlejiraissues:issues=$as.param($itests)|columns=summary;assignee;priority;status|style=progress}

+++<a name="EJB3RoadMap-Examples">++++++</a>+++

== Examples

. set( $examples = $jira.getIssue("OPENEJB-342").subTasks) {swizzlejiraissues:issues=$as.param($examples)|columns=summary;assignee;priority;status|style=progress}

\{swizzlejira}
