= Securing a Web Service

Web Services are a very common way to implement a Service Oriented Architecture (SOA).

There are lots of web service standards/specifications (XML, SOAP, WSDL, UUDI, WS-*, ...) coming from organizations like W3C, OASIS, WS-I, ...
And there are java web service standards like JAX-WS 1.x (JSR 181), JAX-WS 2.0 (JSR 224).

OpenEJB provides a standard way to implement web services transport protocol throughout the JAX-WS specification.
Java basic standards for web services (JAX-WS) do lack some features that are required in most real world applications, e.g.
standard ways for handling security and authentication (there is no java specification for Oasis's WS-Security specification).

OpenEJB provides two mechanisms to secure webservices - HTTP authentication and WS-Security:

HTTPS : works at the transport level, enables a point-to-point security.
It has no impact on developments.
It allows you :

. To secure data over the network with data encrypted during transport
. To identify the end user with SSLv3 with client certificate required
. OpenEJB supports BASIC authentication over HTTP(S), using the configured JAAS provider.
This will honour any EJB security roles you have setup using @RolesAllowed.
See the webservice-security example in the OpenEJB codebase http://svn.apache.org/repos/asf/tomee/tomee/trunk/examples/

_Warning: Currently only BASIC is the only HTTP authentication mechanism available when running OpenEJB standalone or in a unit test, but we hope to support DIGEST in the future._

WS-Security: works at the message (SOAP) level, enables a higher-level security,  Nowadays, SOAP implementations use other protocols than just HTTP so we need to apply security to the message itself and not only at the transport layer.
Moreover, HTTPS can only be used for securing point-to-point services which tend to decrease with Enterprise Service Bus for example.

The Oasis organization has defined a standard (part of well-known WS-*) which aims at providing high level features in the context of web services: WS-Security.
It provides a standard way to secure your services above and beyond transport level protocols such as HTTPS.
WS-Security relies on other standards like XML-Encryption.

Main features are:

. Timestamp a message,
. Pass credentials (plain text and/or ciphered) between services,
. Sign messages,
. Encrypt messages or part of messages.

Again, JAX-WS doesn't standardize security for web services.
OpenEJB provides a common and highly configurable way to configure WS-Security in association with the JAX-WS usage without vendor dependence.
Internally, OpenEJB integrates Apache WSS4J as the WS-Security implementation.
To use the integration, you will need to configure WSS4J using the _openejb-jar.xml_.

_Warning: the proposed WS-Security integration is only used at server side.
Currently, WS-Security client configuration is not managed by OpenEJB.
You can use the JAX-WS API to create a stub and then rely on the implementation to set up WS-Security properties._

This configuration file lets you set up incoming and outgoing security parameters.
Incoming and outgoing configuration is independent so that you can configure either one or the other or both.
You can decide to check client credentials for incoming messages and sign outgoing messages (response).



= Configuration principles

The configuration is made in the _openejb-jar.xml_.
Each endpoint web service can provide a set of properties to customize WS-Security behavior through the +++<properties>+++element.
The content of this element is consistent with the overall structure of *openejb.xml*.
The format for properties is the same as if you would use a common java property file.+++</properties>+++

 <properties>
   wss4j.in.action = UsernameToken
   wss4j.in.passwordType = PasswordDigest
   wss4j.in.passwordCallbackClass=org.superbiz.calculator.CustomPasswordHandler
 </properties>

In order to recover WSS4J properties both for input and output, we use naming conventions.
Each property is made of+++<wss4j>+++.<in|out>.+++<wss4j property="" name="">+++=+++<wss4j property="" value="">+++For example : *wss4j.in.action = UsernameToken*  # Examples A full example (webservice-ws-security) is available with OpenEJB Examples.+++</wss4j>++++++</wss4j>++++++</wss4j>+++
