= Apache TomEE and security
:index-group: Configuration
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published

Rather than providing its own security implementation, TomEE makes full use of the security features that are part of Tomcat.
Any Catalina realm is supported or you can provide your own security module using the login.config file.

For example, to add some simple security to the http://tomee.apache.org/examples-trunk/webapps/moviefun/README.html[moviefun application] , all we would need to do is:

. Add some users to the tomcat-users.xml file
. Add the necessary @DefineRoles and @RolesAllowed annotations on MoviesImpl
. Add some security config to do HTTP Basic authentication to web.xml Webservice security is also looked after -- username/password based security (HTTP basic, or WS-Security) uses the same Tomcat security.
Certificate based security is also available.

To put it short,

* TomEE uses Tomcat's Security Realm
* Extra TomEE layer adds support for JAAS JACC WS Security
* Supports any org.apache.catalina.Realm implementation
* E.g.
add users to $CATALINA_BASE/conf/tomcat-users.xml
* Alternatively use login.config to provide your own security module

== See Also: xref:tomee-jaas.adoc[TomEE and JAAS]
